name: .NET

on:
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore SimpleInventoryManagement/SimpleInventoryManagement.sln
    - name: Build
      run: dotnet build SimpleInventoryManagement/SimpleInventoryManagement.sln --no-restore
    - name: Test
      run: dotnet test SimpleInventoryManagement/SimpleInventoryManagement.sln --no-build --verbosity normal
